
    create table books (
        available_copies integer not null,
        price numeric(38,2) not null,
        published_year integer,
        id bigint generated by default as identity,
        isbn varchar(13) unique,
        author varchar(120) not null,
        title varchar(200) not null,
        primary key (id)
    );

    create table orders (
        price_at_purchase numeric(8,2) not null,
        book_id bigint not null,
        created_at timestamp(6) with time zone not null,
        id bigint generated by default as identity,
        user_id bigint not null,
        transactionid varchar(255) not null,
        primary key (id)
    );

    create table users (
        id bigint generated by default as identity,
        jmbg varchar(13) not null unique,
        role varchar(20) not null check ((role in ('USER','ADMIN'))),
        ime varchar(50) not null,
        prezime varchar(50) not null,
        email varchar(100) not null unique,
        password_hashed varchar(255) not null,
        primary key (id)
    );

    alter table if exists orders 
       add constraint FKi0uonhq5m6jxxlt5smyobjrdv 
       foreign key (book_id) 
       references books;

    alter table if exists orders 
       add constraint FK32ql8ubntj5uh44ph9659tiih 
       foreign key (user_id) 
       references users;
