spring.config.import=optional:file:.env[.properties]
spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/bookstore
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.flyway.enabled=true

spring.jpa.open-in-view=false

app.jwt.secret=${JWT_SECRET}
app.jwt.expiration=86400000

spring.mail.host=localhost
spring.mail.port=1025
app.mail.from=noreply@biblioteka.local

logging.level.org.springframework.security=DEBUG

