CREATE TABLE users (
                       id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       jmbg            VARCHAR(13)  NOT NULL UNIQUE,
                       ime             VARCHAR(50)  NOT NULL,
                       prezime         VARCHAR(50)  NOT NULL,
                       role            VARCHAR(20)  NOT NULL CHECK (role IN ('USER', 'ADMIN')),
                       email           VARCHAR(100) NOT NULL UNIQUE,
                       password_hashed VARCHAR(255) NOT NULL
);

CREATE INDEX idx_users_email ON users(email);