CREATE TABLE books (
                       id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       title            VARCHAR(200)  NOT NULL,
                       author           VARCHAR(120)  NOT NULL,
                       isbn             VARCHAR(13)   NOT NULL UNIQUE,
                       published_year   INTEGER       NOT NULL,
                       available_copies INTEGER       NOT NULL,
                       price            NUMERIC(8,2) NOT NULL,

                       CONSTRAINT chk_books_copies_non_negative CHECK (available_copies >= 0)
);

CREATE INDEX idx_books_title ON books(title);