CREATE TABLE orders (
                        id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        user_id           BIGINT       NOT NULL REFERENCES users(id),
                        book_id           BIGINT       NOT NULL REFERENCES books(id),
                        price_at_purchase NUMERIC(8,2) NOT NULL,
                        transaction_id     VARCHAR(255) NOT NULL,
                        created_at        TIMESTAMPTZ  NOT NULL
);

CREATE INDEX idx_orders_user_id ON orders(user_id);
CREATE INDEX idx_orders_book_id ON orders(book_id);