name: Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Grant execute permission to mvnw
        run: chmod +x ./mvnw

      - name: Run all tests
        run: ./mvnw verify

      - name: Test report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Test results
          path: '**/target/*-reports/TEST-*.xml'
          reporter: java-junit